# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 19.x, 20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run production --if-present
    - run: npx rimraf node_modules
    - name: Delete answers branches
      uses: dawidd6/action-delete-branch@v3.1.0
      with:
        branches: latest-${{ matrix.node-version }}
        soft_fail: true
    - name: Save answers to different branch
      uses: sylvanld/action-storage@v1
      with:
        storage-branch: latest-${{ matrix.node-version }}
        src: '*'
        dst: /
